from pathlib import Path

# ----------------------------------------------------------------------------
# Reproducibility
# ----------------------------------------------------------------------------
SEED = 42

# ----------------------------------------------------------------------------
# The 14 thoracic disease labels (canonical NIH ChestX-ray14 order).
# "No Finding" is NOT a label here -- it is represented as an all-zero vector.
# ----------------------------------------------------------------------------
LABELS = [
    "Atelectasis", "Cardiomegaly", "Effusion", "Infiltration", "Mass",
    "Nodule", "Pneumonia", "Pneumothorax", "Consolidation", "Edema",
    "Emphysema", "Fibrosis", "Pleural_Thickening", "Hernia",
]
NUM_LABELS = len(LABELS)

# ----------------------------------------------------------------------------
# Paths  (override DATA_DIR on Kaggle / locally as noted above)
# ----------------------------------------------------------------------------
DATA_DIR = Path("/kaggle/input/datasets/organizations/nih-chest-xrays/data")
CSV_NAME = "Data_Entry_2017.csv"               # main metadata file
TRAIN_VAL_LIST = "train_val_list.txt"          # official patient-disjoint split
TEST_LIST = "test_list.txt"                     # official patient-disjoint split

OUTPUT_DIR = Path("/kaggle/working/outputs")
CHECKPOINT_DIR = OUTPUT_DIR / "checkpoints"
FIGURE_DIR = OUTPUT_DIR / "figures"
METRIC_DIR = OUTPUT_DIR / "metrics"

# ----------------------------------------------------------------------------
# Image / preprocessing
# ----------------------------------------------------------------------------
IMG_SIZE = 224
# ImageNet normalization (used because backbones are ImageNet-pretrained;
# grayscale X-rays are replicated to 3 channels).
IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

# ----------------------------------------------------------------------------
# Training
# ----------------------------------------------------------------------------
BATCH_SIZE = 64
NUM_WORKERS = 2
EPOCHS = 8                 # raise to 12-15 if you have GPU time to spare
LR = 1e-4
WEIGHT_DECAY = 1e-5
VAL_FRACTION = 0.10        # carved out of train_val, patient-wise
USE_FOCAL_LOSS = False     # if True, uses focal loss; else weighted BCE
# Default decision threshold for F1/precision/recall (per-label tuning optional)
DEFAULT_THRESHOLD = 0.5

# --- Limited-compute knobs (free Colab / T4) ----------------------------------
# Subsample TRAIN by this many patients (None = use all ~24k train patients).
# ~3000 patients ~= 10k images -> trains fast enough to finish in one session.
MAX_TRAIN_PATIENTS = None
# Cap val/test to this many images each (None = full). Speeds up per-epoch eval.
MAX_EVAL_IMAGES = None

# ----------------------------------------------------------------------------
# RAG / LLM
# ----------------------------------------------------------------------------
EMBED_MODEL = "all-MiniLM-L6-v2"   # sentence-transformers, small + free
TOP_K = 4                           # retrieved chunks per query
LLM_PROVIDER = "gemini"             # "gemini" or "anthropic"
GEMINI_MODEL = "gemini-3.5-flash"
ANTHROPIC_MODEL = "claude-sonnet-4-5"

# Probability bands -> uncertainty language used in the grounded summary
CONFIDENCE_BANDS = [
    (0.80, "high probability"),
    (0.50, "moderate probability"),
    (0.00, "low probability"),
]

DISCLAIMER = (
    "This output is generated by an automated, assistive research tool and is "
    "NOT a medical diagnosis. It has not been reviewed or approved for clinical "
    "use. All findings are probabilistic and may be incorrect. Any clinical "
    "decision must be made by a qualified radiologist or physician using the "
    "original imaging and full patient context."
)


def ensure_dirs():
    for d in (OUTPUT_DIR, CHECKPOINT_DIR, FIGURE_DIR, METRIC_DIR):
        Path(d).mkdir(parents=True, exist_ok=True)
